### ISSUE TITLE
Invalid selector error for toggle menu

### ISSUE THREAD

**Issue by johnmcconda** [dkjha52/SeleniumNUnitExtentReport#1]
When I try to run the tests, I'm getting an invalid selector on the toggle menu that brings up the login link.

Message: 
    OpenQA.Selenium.InvalidSelectorException : invalid selector: Unable to locate an element with the xpath expression //a[@id=’menu-toggle’]/i because of the following error:
    SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//a[@id=’menu-toggle’]/i' is not a valid XPath expression.
      (Session info: chrome=83.0.4103.61)
  Stack Trace: 
    RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
    RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
    RemoteWebDriver.FindElement(String mechanism, String value)
    RemoteWebDriver.FindElementByXPath(String xpath)
    <>c__DisplayClass19_0.<XPath>b__0(ISearchContext context)
    By.FindElement(ISearchContext context)
    RemoteWebDriver.FindElement(By by)
    LoginPage.goToToggleMenu() line 32
    LoginTest.test_invalidLogin() line 37

**Comment by dkjha52** [comment]
I tried to reproduce this using the same browser version chrome=83.0.4103.61. Its working fine at my end. I am getting one pass and fail (with screenshot) result.
However as per your failure log, it seems issue is related to the single quotes in the object (before and after menu-toggle) -
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//a[@id=’menu-toggle’]/i'

It should be look like below - 
String toggle_menu = "//a[@id='menu-toggle']/i";

Please try and let me know if you still face the issue.

**Comment by johnmcconda** [comment]
Thanks. I was using code from a tutorial that I copy/pasted, so that was probably it.

On Jul 1, 2020, at 6:06 AM, Dhirendra <notifications@github.com<mailto:notifications@github.com>> wrote:



I tried to reproduce this using the same browser version chrome=83.0.4103.61. Its working fine at my end. I am getting one pass and fail (with screenshot) result.
However as per your failure log, it seems issue is related to the single quotes in the object (before and after menu-toggle) -
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '//a[@id<https://github.com/id>=’menu-toggle’]/i'

It should be look like below -
String toggle_menu = "//a[@id<https://github.com/id>='menu-toggle']/i";

Please try and let me know if you still face the issue.

**Comment by dkjha52** [comment]
Closing this issue.
